# Generated by Django 4.0.1 on 2022-01-11 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_products'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
