# Generated by Django 4.0.1 on 2022-01-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_alter_products_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='img1',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
