# Generated by Django 4.0.1 on 2022-01-11 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0007_alter_products_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='back_camera',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='battery',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminApp.subcategory'),
        ),
        migrations.AddField(
            model_name='products',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='products',
            name='front_camera',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='img2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='img3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='offer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='rom',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='VariantAndPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.products')),
            ],
            options={
                'db_table': 'variantandprice',
            },
        ),
    ]
