# Generated by Django 4.0.1 on 2022-01-11 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0008_products_back_camera_products_battery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantandprice',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminApp.products'),
        ),
    ]
