# Generated by Django 4.0.1 on 2022-01-14 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0009_alter_variantandprice_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 11, 54, 6, 578026)),
        ),
    ]
