# Generated by Django 4.0.1 on 2022-01-14 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0010_alter_products_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
