# Generated by Django 3.2 on 2022-01-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0014_rename_annerimg_banner_bannerimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='product_id',
            new_name='p_id',
        ),
    ]
