# Generated by Django 3.2 on 2022-02-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0019_coupen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupen',
            name='coupen_offer',
            field=models.PositiveBigIntegerField(),
        ),
    ]
