# Generated by Django 3.2 on 2022-02-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0022_auto_20220209_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='processor',
            field=models.CharField(choices=[('Snapdragon', 'Snapdragon'), ('MediaTek', 'MediaTek'), ('bionic', 'bionic')], default='Snapdragon', max_length=20),
        ),
    ]
