# Generated by Django 3.2 on 2022-02-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0024_alter_products_processor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
