# Generated by Django 4.0.1 on 2022-01-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='block',
            field=models.BooleanField(default=0),
        ),
    ]
