# Generated by Django 3.2 on 2022-01-18 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0011_alter_products_date'),
        ('userApp', '0008_remove_customuser_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.products')),
            ],
        ),
    ]
