# Generated by Django 3.2 on 2022-01-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0009_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
