# Generated by Django 3.2 on 2022-01-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0010_alter_cart_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.BigIntegerField(default=1),
        ),
    ]
