# Generated by Django 3.2 on 2022-01-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0012_alter_cart_variant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
