# Generated by Django 3.2 on 2022-01-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0014_alter_cart_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=10)),
                ('zipcode', models.CharField(max_length=6)),
                ('address', models.TextField()),
            ],
        ),
    ]
