# Generated by Django 3.2 on 2022-01-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0021_auto_20220126_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='cash on delivery', max_length=100),
        ),
    ]
