# Generated by Django 3.2 on 2022-01-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0023_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_id',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='shahin salim, kerla india ,654789 , 0101010101'),
        ),
    ]
