# Generated by Django 3.2 on 2022-01-31 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0015_rename_product_id_banner_p_id'),
        ('userApp', '0025_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='variant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='adminApp.variantandprice'),
        ),
    ]
